from typing import Type, Union

from app.models.yields.product import (Argentina, Australia, Austria, Bahrain,
                                       Bangledesh, Belgium, Botswana, Brazil,
                                       Bulgaria, Canada, Chile, China,
                                       Colombia, Crotia, Cyprus,
                                       Czech_Republic, Egypt, France, Germany,
                                       Greece, Hong_Kong, Hungary)

hashmap = {
    "Argentina": Argentina,
    "argentina": Argentina,
    "Australia": Australia,
    "australia": Australia,
    "Austria": Austria,
    "austria": Austria,
    "Bahrain": Bahrain,
    "bahrain": Bahrain,
    "Bangledesh": Bangledesh,
    "bangledesh": Bangledesh,
    "Belgium": Belgium,
    "belgium": Belgium,
    "Botswana": Botswana,
    "botswana": Botswana,
    "Brazil": Brazil,
    "brazil": Brazil,
    "Bulgaria": Bulgaria,
    "bulgaria": Bulgaria,
    "Canada": Canada,
    "canada": Canada,
    "Chile": Chile,
    "chile": Chile,
    "China": China,
    "china": China,
    "Colombia": Colombia,
    "colombia": Colombia,
    "Crotia": Crotia,
    "crotia": Crotia,
    "Cyprus": Cyprus,
    "cyprus": Cyprus,
    "Czech Republic": Czech_Republic,
    "czech republic": Czech_Republic,
    "Egypt": Egypt,
    "egypt": Egypt,
    "France": France,
    "france": France,
    "Germany": Germany,
    "germany": Germany,
    "Greece": Greece,
    "greece": Greece,
    "Hong Kong": Hong_Kong,
    "hong kong": Hong_Kong,
    "Hungary": Hungary,
    "hungary": Hungary,
}


def get_class(nation: str) -> Type[Union[Argentina, Australia, Austria,
                                         Bahrain, Bangledesh, Belgium,
                                         Botswana, Brazil, Bulgaria,
                                         Canada, Chile, China, Colombia,
                                         Crotia, Cyprus, Czech_Republic,
                                         Egypt, France, Germany, Greece,
                                         Hong_Kong, Hungary]]:
    if nation not in hashmap:
        raise ValueError(f"Invalid nation: {nation} check the documentation for valid nations!")
    return hashmap[nation]
