name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install types-PyMySQL
        python3 -m pip install types-requests
        
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
